apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-connect-config
  namespace: default
data:
  bootstrap.servers: "<MSK_BOOTSTRAP_SERVERS>"  
  key.converter: "org.apache.kafka.connect.json.JsonConverter"
  value.converter: "org.apache.kafka.connect.json.JsonConverter"
  connector.class: "io.confluent.connect.s3.S3SinkConnector"
  topics: "<TOPIC_NAME>"  
  s3.bucket.name: "<S3_BUCKET_NAME>"  
  s3.region: "<S3_REGION>" 
  flush.size: "1000"